name: Test, Build, Deploy and Api-Test

on:
  pull_request:
    branches:
      - develop
defaults:
  run:
    working-directory: Songify
    
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify
        run: mvn -B clean verify -DskipTests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kbe-songify" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          #appdir: "Songify" # subfolder to deploy
  test-api:
      runs-on: ubuntu-latest
      needs: build
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
    # Install Node on the runner
        - name: Install Node
          uses: actions/setup-node@v2
          with: 
            node-version: '16.x'

      
      # Install the newman command line utility
        - name: Install newman
          run: |
            npm install -g newman

    # Run the POSTMAN collection
        - name: Run API Tests
          run: newman run "postman_collection.json"
          
